= Resources
:source-highlighter: highlightjs

Below you can find documentation about the different resources exposed in this service.

[[resources-users]]
== users
Users resource.

=== Create a new User
A 'POST' request with the user information in the JSON body is used to create a new user.

==== Request Structure
operation::users-post[snippets='http-request,request-fields,curl-request']

==== Response Structure
operation::users-post[snippets='http-response,response-headers']

=== Get User Details
A 'GET' request with the user-id is used to retrieve a specific user.

==== Request Structure
operation::user-get[snippets='http-request,path-parameters,curl-request']

==== Response Structure
operation::user-get[snippets='http-response,response-fields,response-headers']

=== Get All Users
A 'GET' request is used to retrieve all users.

==== Request Structure
operation::users-get[snippets='http-request,curl-request']

==== Response Structure
operation::users-get[snippets='http-response,response-fields,response-headers']
